|  ID | Year |                                                                                       Title                                                                                       |                                  Task                                 |                              Model                             |
|:---:|:----:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:---------------------------------------------------------------------:|:--------------------------------------------------------------:|
|  1  | 2021 |              90% Accuracy for Photoplethysmography-Based Non-Invasive Blood Glucose Prediction by Deep Learning with Cohort Arrangement and Quarterly Measured HbA1c              |                             Blood glucose                             |                               CNN                              |
|  2  | 2022 |                               A Comparison of Signal Combinations for Deep Learning-Based Simultaneous Sleep Staging and Respiratory Event Detection                              |                              Sleep health                             |                            U-net/CNN                           |
|  3  | 2021 |                                            A Continuous Blood Pressure Estimation Method Using Photoplethysmography by GRNN-Based Model                                           |                             Blood pressure                            |                     Encoder-Decoder / GRNN                     |
|  4  | 2023 |                                           A Deep Learning and Fast Wavelet Transform-Based Hybrid Approach for Denoising of PPG Signals                                           |                           Signal processing                           |                   fast wavelet transform + FC                  |
|  5  | 2023 |                               A Deep Learning Approach for Atrial Fibrillation Classification Using Multi-Feature Time Series Data from ECG and PPG                               |                         Cardiovascular system                         |                            CNN + RNN                           |
|  6  | 2022 |                                                             A Deep Learning Approach to Estimate SpO2 from PPG Signals                                                            |                           Respiratory system                          |                    handcrafted-features + FC                   |
|  7  | 2017 |                                         A Deep Learning Approach to Monitoring and Detecting Atrial Fibrillation using Wearable Technology                                        |                         Cardiovascular system                         |                             CWT+CNN                            |
|  8  | 2021 |                                                        A Deep Learning Approach to Predict Blood Pressure from PPG Signals                                                        |                             Blood pressure                            |                         CRNN(CNN-LSTM)                         |
|  9  | 2021 |                                                       A Deep Learning Approach to Recognize Cognitive Load using PPG Signals                                                      |                             Mental health                             |                          CWT + AlexNet                         |
|  10 | 2019 |                                                  A Deep Neural Network-Based Pain Classifier Using a Photoplethysmography Signal                                                  |                                 Others                                |                  deep belief network (DBN), FC                 |
|  11 | 2021 |                                        A deep transfer learning approach for wearable sleep stage classification with photoplethysmography                                        |                              Sleep health                             |                               RNN                              |
|  12 | 2022 |      A dynamic reconfigurable wearable device to acquire high quality PPG signal and robust heart rate estimate based on deep learning algorithm for smart healthcare system      |                         Cardiovascular system                         |                         CRNN(CNN-LSTM)                         |
|  13 | 2022 |                             A Flexible Deep Learning Architecture for Temporal Sleep Stage Classification Using Accelerometry and Photoplethysmography                            |                              Sleep health                             |                            U-net/CNN                           |
|  14 | 2023 |                                 A Machine Learning Approach to the Non-Invasive Estimation of Continuous Blood Pressure Using Photoplethysmography                                |                             Blood pressure                            |                       Encoder-decoder/FC                       |
|  15 | 2020 |                                       A multistage deep neural network model for blood pressure estimation using photoplethysmogram signals                                       |                             Blood pressure                            |                         CRNN(CNN-LSTM)                         |
|  16 | 2021 |                                      A multi-type features fusion neural network for blood pressure prediction based on photoplethysmography                                      |                             Blood pressure                            |                           CNN / LSTM                           |
|  17 | 2022 |                                    A new deep learning framework based on blood pressure range constraint for continuous cuffless BP estimation                                   |                             Blood pressure                            |                               CNN                              |
|  18 | 2023 |        A novel CS-NET architecture based on the unification of CNN, SVM and super-resolution spectrogram to monitor and classify blood pressure using photoplethysmography        |                             Blood pressure                            |                             CNN-SVM                            |
|  19 | 2022 |                                               A Novel Rapid Assessment of Mental Stress by Using PPG Signals Based on Deep Learning                                               |                             Mental health                             |                            GoogLeNet                           |
|  20 | 2022 |                                 A photoplethysmography-based diagnostic support system for obstructive sleep apnea using deep learning approaches                                 |                              Sleep health                             |                       LSTM, TCN, TCN-LSTM                      |
|  21 | 2021 |                             A Real-Time Affective Computing Platform Integrated with AI System-on-Chip Design and Multimodal Signal Processing System                             |                             Mental health                             |                         CRNN(CNN+LSTM)                         |
|  22 | 2022 |                                               A Refined Blood Pressure Estimation Model Based on Single Channel Photoplethysmography                                              |                             Blood pressure                            |                       BiLSTM + attention                       |
|  23 | 2021 |                                                  A Stable PPG-based Biometric Method using Dynamic Time Warping and Deep Learning                                                 |                        Biometric identification                       |                     DTW + CRNN (CNN-LSTM）                     |
|  24 | 2022 |                                                    A Stress Detection Model Based on LSTM Network Using Solely Raw PPG Signals                                                    |                             Mental health                             |                              LSTM                              |
|  25 | 2022 |                                     A Teenager Physical Fitness Evaluation Model Based on 1D-CNN with LSTM and Wearable Running PPG Recordings                                    |                                 Others                                |                        1D-CNN with LSTM                        |
|  26 | 2023 |                                A training pipeline of an arrhythmia classifier for atrial fibrillation detection using Photoplethysmography signal                                |                         Cardiovascular system                         |                CNN, LSTM, CNN-LSTM, Transformer                |
|  27 | 2019 |                                     ActiPPG: Using deep neural networks for activity recognition from wrist-worn photoplethysmography sensors                                     |                       Human activity recognition                      |                         CRNN (CNN-LSTM)                        |
|  28 | 2019 |                                          Ambulatory Atrial Fibrillation Monitoring Using Wearable Photoplethysmography with Deep Learning                                         |                         Cardiovascular system                         |                               CNN                              |
|  29 | 2021 |                               An End-to-End and Accurate PPG-based Respiratory Rate Estimation Approach Using Cycle Generative Adversarial Networks                               |                           Respiratory system                          |              Cycle Generative Adversarial Networks             |
|  30 | 2021 |                  An Estimation Method of Continuous Non-Invasive Arterial Blood Pressure Waveform Using Photoplethysmography: A U-Net Architecture-Based Approach                 |                             Blood pressure                            |                              U-Net                             |
|  31 | 2021 |                           Applying a Deep Learning Network in Continuous Physiological Parameter Estimation Based on Photoplethysmography Sensor Signals                          |                  Blood pressure/Cardiovascular system                 |                         CRNN (CNN-LSTM)                        |
|  32 | 2021 |                      Assessment of obstructive sleep apnea-related sleep fragmentation utilizing deep learning-based sleep staging from photoplethysmography                      |                              Sleep health                             |                              CRNN                              |
|  33 | 2021 |                       Atrial Fibrillation Classification with Smart Wearables Using Short-Term Heart Rate Variability and Deep Convolutional Neural Networks                      |                         Cardiovascular system                         |                            CNN + HRV                           |
|  34 | 2020 |                                         Atrial fibrillation detection from raw photoplethysmography waveforms: A deep learning application                                        |                         Cardiovascular system                         |                           LSTM, CRNN                           |
|  35 | 2022 |                                      Attention-LRCN: Long-term Recurrent Convolutional Network for Stress Detection from Photoplethysmography                                     |                             Mental health                             |                    CRNN(CNN+LSTM+attention)                    |
|  36 | 2021 |                                 Automatic Sleep Staging in Children with Sleep Apnea using Photoplethysmography and Convolutional Neural Networks                                 |                              Sleep health                             |                               CNN                              |
|  37 | 2020 |                                   Beat-to-Beat Continuous Blood Pressure Estimation Using Bidirectional Long Short-Term MMental healthry Network                                  |                             Blood pressure                            |                             BiLSTM                             |
|  38 | 2022 |                        BePCon: A Photoplethysmography-Based Quality-Aware Continuous Beat-to-Beat Blood Pressure Measurement Technique Using Deep Learning                        |                             Blood pressure                            |                         handcrafted-TCN                        |
|  39 | 2022 |                          Biometric recognition based on scalable end-to-end convolutional neural network using photoplethysmography: A comparative study                          |                        Biometric identification                       |               1D-CNN                                           |
|  40 | 2018 |                                                  BiometricNet: Deep Learning based Biometric Identification using Wrist-Worn PPG                                                  |                        Biometric identification                       |                         CRNN(CNN-LSTM)                         |
|  41 | 2021 |                                              Biosignal classification for human identification based on convolutional neural networks                                             |                        Biometric identification                       |                               CNN                              |
|  42 | 2019 |                                                       BioTranslator: Inferring R-Peaks from Ambulatory Wrist-Worn PPG Signal                                                      |                           ECG reconstruction                          |                       Encoder-Decoder/CNN                      |
|  43 | 2022 |                                              Blood Pressure and Heart Rate Measurements Using Photoplethysmography with Modified LRCN                                             |                  Blood pressure/Cardiovascular system                 |                         CRNN (CNN-LSTM)                        |
|  44 | 2019 |                                        Blood Pressure Assessment with Differential Pulse Transit Time and Deep Learning: A Proof of Concept                                       |                             Blood pressure                            |     restricted Boltzmann machine artificial neural networks    |
|  45 | 2019 |                                           Blood Pressure Estimation from Photoplethysmogram Using a Spectro-Temporal Deep Neural Network                                          |                             Blood pressure                            |                            CNN, RNN                            |
|  46 | 2022 |                                          Blood Pressure Estimation from Photoplethysmography Signals by Applying Deep Learning Techniques                                         |                             Blood pressure                            |                               CNN                              |
|  47 | 2021 |                  Blood Pressure Morphology Assessment from Photoplethysmogram and DMental healthgraphic Information Using Deep Learning with Attention Mechanism                  |                             Blood pressure                            |                       Encoder-Decoder/GRU                      |
|  48 | 2021 |                                     BP-Net: Efficient Deep Learning for Continuous Arterial Blood Pressure Estimation using Photoplethysmogram                                    |                             Blood pressure                            |                            U-Net/CNN                           |
|  49 | 2020 |                                                Calibration-free Blood Pressure Assessment Using An Integrated Deep Learning Method                                                |                             Blood pressure                            |                               CNN                              |
|  50 | 2022 |                                                CapNet: A Deep Learning-based Framework for Estimation of Capnograph Signal from PPG                                               |                           Respiratory system                          |                    Encoder-Decoder/CNN, LSTM                   |
|  51 | 2021 |                                    CardioGAN: Attentive Generative Adversarial Network with Dual Discriminators for Synthesis of ECG from PPG.                                    |                           ECG reconstruction                          |                               GAN                              |
|  52 | 2020 |                                                       CardioNet: Deep Learning Framework for Prediction of CVD Risk Factors                                                       |           Blood glucose/Blood pressure/Cardiovascular system          |                               CNN                              |
|  53 | 2023 |                                     Cardiovascular risk detection using Harris Hawks optimization with ensemble learning model on PPG signals                                     |                             Blood pressure                            |                            AE/Others                           |
|  54 | 2022 |                 Classification of Blood Pressure Levels Based on Photoplethysmogram and Electrocardiogram Signals with a Concatenated Convolutional Neural Network                |                             Blood pressure                            |                               CNN                              |
|  55 | 2022 |                                       Classification of Physical Exercise Activity from ECG, PPG and IMU Sensors using Deep Residual Network                                      |                       Human activity recognition                      |                           ResNet + SE                          |
|  56 | 2023 |                                          Classification of pulmonary arterial pressure using photoplethysmography and bi-directional LSTM                                         |                             Blood pressure                            |                             BiLSTM                             |
|  57 | 2022 |                                                                    Classifying sepsis from photoplethysmography                                                                   |                                 Others                                |                             Res-CNN                            |
|  58 | 2020 |                                                          Clinical grade SpO2 prediction through semi-supervised learning                                                          |                           Respiratory system                          |                               CNN                              |
|  59 | 2022 |                    CNN-Based Deep Learning Network for Human Activity Recognition During Physical Exercise from Accelerometer and Photoplethysmographic Sensors                   |                       Human activity recognition                      |                               CNN                              |
|  60 | 2022 |                            Continuous Blood Pressure Estimation Based on Multi-Scale Feature Extraction by the Neural Network With Multi-Task Learning                            |                             Blood pressure                            |                               CNN                              |
|  61 | 2021 |                               Continuous Blood Pressure Estimation Using Exclusively Photopletysmography by LSTM-Based Signal-to-Signal Translation                               |                             Blood pressure                            |                      Encoder-Decoder/LSTM                      |
|  62 | 2023 |                     Continuous cuffless blood pressure monitoring using photoplethysmography‑based PPG2BP‑net for high intrasubject blood pressure variations                     |                             Blood pressure                            |                               CNN                              |
|  63 | 2019 |                              CorNET: Deep Learning Framework for PPG-Based Heart Rate Estimation and Biometric Identification in Ambulant Environment                             |             Biometric identification/Cardiovascular system            |                         CRNN(CNN-LSTM)                         |
|  64 | 2023 |                                                         COVID-19 Detection Using Photoplethysmography and Neural Networks                                                         |                                 Others                                |                               CNN                              |
|  65 | 2019 |                                            Cuffless Blood Pressure Estimation from only the Waveform of Photoplethysmography using CNN                                            |                             Blood pressure                            |                               CNN                              |
|  66 | 2021 |                                      Cuff-Less Blood Pressure Estimation From Photoplethysmography via Visibility Graph and Transfer Learning                                     |                             Blood pressure                            |                            VG + CNN                            |
|  67 | 2021 |                                         Cuffless blood pressure estimation from PPG signals and its derivatives using deep learning models                                        |                             Blood pressure                            |                     handcraft-RNN-attention                    |
|  68 | 2021 |                                                    Cuff-Less Blood Pressure Estimation via Small Convolutional Neural Networks                                                    |                             Blood pressure                            |                   VG + modified LeNet-5 (CNN)                  |
|  69 | 2023 |                                               Cuff-Less Blood Pressure Prediction Based on Photoplethysmography and Modified ResNet                                               |                             Blood pressure                            |                         modified ResNet                        |
|  70 | 2022 |    Cuff-Less Blood Pressure Prediction from ECG and PPG Signals Using Fourier Transformation and Amplitude Randomization Preprocessing for Context Aggregation Network Training   |                             Blood pressure                            |                       Encoder-Decoder/CNN                      |
|  71 | 2019 |                                                   Cuffless Deep Learning-Based Blood Pressure Estimation for Smart Wristwatches                                                   |                             Blood pressure                            |                          handcraft-FC                          |
|  72 | 2019 |                                   Data-driven assessment of cardiovascular ageing through multisite photoplethysmography and electrocardiography                                  |                         Cardiovascular system                         |                               CNN                              |
|  73 | 2022 |                              Deduction learning for precise noninvasive measurements of blood glucose with a dozen rounds of data for model training                              |                             Blood glucose                             |                               CNN                              |
|  74 | 2022 |                                              Deep convolutional neural network-based signal quality assessment for photoplethysmogram                                             |                           Signal processing                           |                               CNN                              |
|  75 | 2021 |                                 Deep learning algorithm evaluation of hypertension classification in less photoplethysmography signals conditions                                 |                             Blood pressure                            |                         CRNN (CNN-LSTM)                        |
|  76 | 2019 |                                   Deep Learning approaches for Plethysmography Signal Quality Assessment in the Presence of Atrial Fibrillation                                   |                           Signal processing                           |                          CNN, LSTM, FC                         |
|  77 | 2019 |                              Deep Learning Approaches to Detect Atrial Fibrillation Using Photoplethysmographic Signals: Algorithms Development Study                             |                         Cardiovascular system                         |                         1D-CNN and RNN                         |
|  78 | 2018 |                                            Deep Learning Based Atrial Fibrillation Detection Using Wearable Photoplethysmography Sensor                                           |                Cardiovascular system/Signal processing                |                            CNN, CRNN                           |
|  79 | 2021 |                                               Deep Learning based non-invasive diabetes predictor using Photoplethysmography signals                                              |                             Blood glucose                             |                               CNN                              |
|  80 | 2022 |                                                  Deep Learning Based Obstructive Sleep Apnea Detection for e-health Applications                                                  |                              Sleep health                             |                         CNN-LSTM, LSTM                         |
|  81 | 2020 |                                        Deep learning enables sleep staging from photoplethysmogram for patients with suspected sleep apnea                                        |                              Sleep health                             |                              CRNN                              |
|  82 | 2020 |                     Deep Learning for Heart Rate Estimation From Reflectance Photoplethysmography With Acceleration Power Spectrum and Acceleration Intensity                     |                         Cardiovascular system                         |                         CNN-LSTM(CRNN)                         |
|  83 | 2022 |                                                           Deep learning for predicting respiratory rate from biosignals                                                           |                           Respiratory system                          |                    CNN, LSTM, CRNN(CNN-LSTM)                   |
|  84 | 2021 |                                         Deep Learning Framework for Biometric Identification from Wrist-Worn PPG With Acceleration Signals                                        |                        Biometric identification                       |                        CRNN(CNN-BiLSTM)                        |
|  85 | 2021 |                                               Deep Learning Fused Wearable Pressure and PPG Data for Accurate Heart Rate Monitoring                                               |                         Cardiovascular system                         |                               FC                               |
|  86 | 2022 |                                                         Deep Learning Model for Blood Pressure Estimation from PPG Signal                                                         |                             Blood pressure                            |                               CNN                              |
|  87 | 2021 |                                     Deep Learning Model with Individualized Finetuning for Dynamic and Beat-to-Beat Blood Pressure Estimation                                     |                             Blood pressure                            |                         CRNN (CNN-GRU)                         |
|  88 | 2021 |                                       Deep learning models for cuffless blood pressure monitoring from PPG signals using attention mechanism                                      |                             Blood pressure                            |                          RNN-attention                         |
|  89 | 2023 |                                               Deep Learning Models for Stress Analysis in University Students: A Sudoku-Based Study                                               |                             Mental health                             |                            CNN, CRNN                           |
|  90 | 2021 |                                                       Deep learning models for the prediction of intraoperative hypotension                                                       |                             Blood pressure                            |                               CNN                              |
|  91 | 2021 |                                                    Deep learning via ECG and PPG signals for prediction of depth of anesthesia                                                    |                                 Others                                |                               CNN                              |
|  92 | 2021 |                            Deep learning-based photoplethysmography classification for peripheral arterial disease detection: a proof-of-concept study                            |                         Cardiovascular system                         |                             AlexNet                            |
|  93 | 2019 |                                                   Deep PPG: Large-Scale Heart Rate Estimation with Convolutional Neural Networks                                                  |                         Cardiovascular system                         |                               CNN                              |
|  94 | 2019 |                          Deep Recurrent Neural Network for Extracting Pulse Rate Variability from Photoplethysmography During Strenuous Physical Exercise                         |                Cardiovascular system/Signal processing                |                             BiLSTM                             |
|  95 | 2022 |                            DeepCNAP: A Deep Learning Approach for Continuous Noninvasive Arterial Blood Pressure Monitoring Using Photoplethysmography                            |                             Blood pressure                            |                              U-Net                             |
|  96 | 2021 |                                              DeepHeart: A Deep Learning Approach for Accurate Heart Rate Estimation from PPG Signals                                              |                Cardiovascular system/Signal processing                |                               CNN                              |
|  97 | 2019 |                                                 DeepHeart: Accurate Heart Rate Estimation from PPG Signals based on Deep Learning                                                 |                         Cardiovascular system                         |                               CNN                              |
|  98 | 2023 |                         Deep‑learning‑based blood pressure estimation using multi channel photoplethysmogram and finger pressure with attention mechanism                         |                             Blood pressure                            |                          CNN-attention                         |
|  99 | 2022 |                                        Detection of Cardiovascular Disease Based on PPG Signals Using Machine Learning with Cloud Computing                                       |                         Cardiovascular system                         |                           1D CNN-LSTM                          |
| 100 | 2018 |                                        Diagnostic assessment of a deep learning system for detecting atrial fibrillation in pulse waveforms                                       |                         Cardiovascular system                         |                               CNN                              |
| 101 | 2023 |                                                               DNN based reliability evaluation for telemedicine data                                                              |                           Signal processing                           |                               FC                               |
| 102 | 2023 |                                                Dual-domain and Multiscale Fusion Deep Neural Network for PPG Biometric Recognition                                                |                        Biometric identification                       |                   CRNN(LSTM-CNN + attention)                   |
| 103 | 2022 |                                                 Dynamic time warping based arrhythmia detection using photoplethysmography signals                                                |                         Cardiovascular system                         |                            DTW + FC                            |
| 104 | 2022 |                                           Embedding Temporal Convolutional Networks for Energy-efficient PPG-based Heart Rate Monitoring                                          |                         Cardiovascular system                         |                               TCN                              |
| 105 | 2019 |                                                  Estimating blood pressure trends and the nocturnal dip from photoplethysmography                                                 |                             Blood pressure                            |                            FC, LSTM                            |
| 106 | 2020 |                                 Estimating Reliability of Signal Quality of Physiological Data from Data Statistics Itself for Real-time Wearables                                |                           Signal processing                           |                          ANN, SVM, RF                          |
| 107 | 2020 |                             Estimation and Tracking of Blood Pressure Using Routinely Acquired Photoplethysmographic Signals and Deep Neural Networks                             |                             Blood pressure                            |                         1D Siamese CNN                         |
| 108 | 2022 |                                    Estimation of Beat-by-Beat Blood Pressure and Heart Rate From ECG and PPG Using a Fine-Tuned Deep CNN Model                                    |                  Blood pressure/Cardiovascular system                 |                         CRNN (CNN-LSTM)                        |
| 109 | 2020 |                                                   Evaluation of the Time Stability and Uniqueness in PPG-Based Biometric System                                                   |                        Biometric identification                       |                       CNN, CRNN(CNN-LSTM)                      |
| 110 | 2022 |                                  Fast Cuffless Blood Pressure Classification with ECG and PPG signals using CNN-LSTM Models in Emergency Medicine                                 |                             Blood pressure                            |                         CRNN (CNN-LSTM)                        |
| 111 | 2019 |                                       Fast Mental healthtion Recognition Based on Single Pulse PPG Signal with Convolutional Neural Network                                       |                             Mental health                             |                               CNN                              |
| 112 | 2021 |                                         Feature Augmented Hybrid CNN for Stress Recognition Using Wrist-based Photoplethysmography Sensor                                         |                             Mental health                             |                               CNN                              |
| 113 | 2021 |                                  Featureless Blood Pressure Estimation Based on Photoplethysmography Signal Using CNN and BiLSTM for IoT Devices                                  |                             Blood pressure                            |                        CRNN (CNN-BiLSTM)                       |
| 114 | 2018 |                                        Features Extraction for Cuffless Blood Pressure Estimation by Autoencoder from Photoplethysmography                                        |                             Blood pressure                            |                               AE                               |
| 115 | 2023 |                                         Fully convolutional neural network and PPG signal for arterial blood pressure waveform estimation                                         |                             Blood pressure                            |                            U-Net/CNN                           |
| 116 | 2022 |                                              Genetic Algorithm-Based Human Mental Stress Detection and Alerting in Internet of Things                                             |                             Mental health                             |                         CRNN(CNN+LSTM)                         |
| 117 | 2020 |                             Genetic Deep Convolutional Autoencoder Applied for Generative Continuous Arterial Blood Pressure via Photoplethysmography                             |                             Blood pressure                            |                   Encoder-decoder, U-Net/CNN                   |
| 118 | 2022 |                                   Gram Matrix-Based Convolutional Neural Network for Biometric Identification Using Photoplethysmography Signal                                   |                        Biometric identification                       |                               CNN                              |
| 119 | 2022 |                                                    Heart rate estimation in PPG signals using Convolutional-Recurrent Regressor                                                   |                         Cardiovascular system                         |                              CRNN                              |
| 120 | 2023 |                                                      Hybrid CNN-SVR Blood Pressure Estimation Model Using ECG and PPG Signals                                                     |                             Blood pressure                            |                             CNN-SVR                            |
| 121 | 2022 |                            Hybrid Convolutional Networks for End-to-End Event Detection in Concurrent PPG and PCG Signals Affected by Motion Artifacts                            |                           Signal processing                           |                               CNN                              |
| 122 | 2021 |                                         Hypertension Risk Assessment from Photoplethysmographic Recordings Using Deep Learning Classifiers                                        |                             Blood pressure                            |                     CNN (Googlenet, ResNet)                    |
| 123 | 2021 |                     Improving the Accuracy in Classification of Blood Pressure from Photoplethysmography Using Continuous Wavelet Transform and Deep Learning                     |                             Blood pressure                            |                               CNN                              |
| 124 | 2021 |                               Imputation of the continuous arterial line blood pressure waveform from non‑invasive measurements using deep learning                               |                             Blood pressure                            |            CNN (SQI), U-Net (modified 1D V-Net)/CNN            |
| 125 | 2022 |                                KD-Informer: A Cuff-Less Continuous Blood Pressure Waveform Estimation Approach Based on Single Photoplethysmography                               |                             Blood pressure                            |                           Transformer                          |
| 126 | 2022 |                                  Lightweight End-to-End Deep Learning Solution for Estimating the Respiration Rate from Photoplethysmogram Signal                                 |                           Respiratory system                          | ResNet, DenseNet, Inception_v1, MobileNet, and ConvMixer (CNN) |
| 127 | 2023 |                Log-Spectral Matching GAN: PPG-Based Atrial Fibrillation Detection can be Enhanced by GAN-Based Data Augmentation With Integration of Spectral Loss                |                Cardiovascular system/Signal processing                |                               GAN                              |
| 128 | 2023 |                                                          Mental Stress Detection Using a Wearable In-Ear Plethysmography                                                          |                             Mental health                             |                            CWT + CNN                           |
| 129 | 2018 |                                         MobileSOFT: U: A Deep Learning Framework to Monitor Heart Rate During Intensive Physical Exercise                                         |                         Cardiovascular system                         |      Restricted Boltzmann Machines and deep belief network     |
| 130 | 2023 |                            MS-Net: Sleep apnea detection in PPG using multi-scale block and shadow module one-dimensional convolutional neural network                            |                              Sleep health                             |                               CNN                              |
| 131 | 2022 |                           Multiclass Arrhythmia Detection and Classification From Photoplethysmography Signals Using a Deep Convolutional Neural Network                          |                         Cardiovascular system                         |                               CNN                              |
| 132 | 2020 |                      Multi-Class Classification of Sleep Apnea/Hypopnea Events Based on Long Short-Term MMental healthry Using a Photoplethysmography Signal                      |                              Sleep health                             |                               CNN                              |
| 133 | 2021 |                                              Multi-Headed Conv-LSTM Network for Heart Rate Estimation during Daily Living Activities                                              |                         Cardiovascular system                         |                         CNN-LSTM(CRNN)                         |
| 134 | 2020 |                                                        Multi-Modal Diagnosis of Infectious Diseases in the Developing World                                                       |                                 Others                                |                      LSTM, CRNN(CNN-LSTM)                      |
| 135 | 2020 |                                                     Multi-task deep learning for cardiac rhythm detection in wearable devices                                                     |                Cardiovascular system/Signal processing                |                               CNN                              |
| 136 | 2022 |                              Neural network based algorithm for a spectrogram classification of wrist-type PPG using high-order harmonics processing                              |                           Signal processing                           |                               CNN                              |
| 137 | 2023 |                    Non-Invasive Arterial Blood Pressure Estimation from Electrocardiogram and Photoplethysmography Signals Using a Conv1D-BiLSTM Neural Network                   |                             Blood pressure                            |                    Encoder-Decoder/CNN, LSTM                   |
| 138 | 2023 |                                  Non-invasive arterial blood pressure measurement and SpO2 estimation using PPG signal: a deep learning framework                                 |                   Blood pressure/Respiratory system                   |                           Transformer                          |
| 139 | 2022 |                                  Non-invasive blood pressure estimation combining deep neural networks with pre-training and partial fine-tuning                                  |                             Blood pressure                            |                              CRNN                              |
| 140 | 2022 |                                 Novel Blood Pressure Waveform Reconstruction from Photoplethysmography using Cycle Generative Adversarial Networks                                |                             Blood pressure                            |              Cycle Generative Adversarial Networks             |
| 141 | 2023 |           Optimized deep neural network models for blood pressure classification using Fourier analysis-based time–frequency spectrogram of photoplethysmography signal           |                             Blood pressure                            |             GoogleNet, DenseNet, and AlexNet (CNN)             |
| 142 | 2021 |                                       P2E-WGAN: ECG Waveform Synthesis from PPG with Conditional Wasserstein Generative Adversarial Networks                                      |                           ECG reconstruction                          |    a conditional Wasserstein generative adversarial network    |
| 143 | 2021 |                                            Perceived Mental Workload Classification Using Intermediate Fusion Multimodal Deep Learning                                            |                             Mental health                             |                          FC, CNN, CRNN                         |
| 144 | 2021 |                          Performance evaluation of deep learning models in detection of different types of arrhythmia using photoplethysmography signals                          |                Cardiovascular system/Signal processing                |                               CNN                              |
| 145 | 2022 |                                         Performance of a Convolutional Neural Network Derived From PPG Signal in Classifying Sleep Stages                                         |                              Sleep health                             |                               CNN                              |
| 146 | 2018 |                                                 Photoplethysmography and Deep Learning: Enhancing Hypertension Risk Stratification                                                |                             Blood pressure                            |                         CWT + GoogleNet                        |
| 147 | 2021 |                                          Personalized Blood Pressure Estimation Using Photoplethysmography: A Transfer Learning Approach                                          |                             Blood pressure                            |                              CRNN                              |
| 148 | 2022 |                                           Photoplethysmogram based vascular aging assessment using the deep convolutional neural network                                          |                         Cardiovascular system                         |                               CNN                              |
| 149 | 2023 |                                                       Photoplethysmogram Biometric Authentication Using a 1D Siamese Network                                                      |                        Biometric identification                       |                             1D-CNN                             |
| 150 | 2020 |                                Photoplethysmography based stratification of blood pressure using multi information fusion artificial neural network                               |                             Blood pressure                            |                            CNN, LSTM                           |
| 151 | 2023 |                                                       Photoplethysmography Driven Hypertension Identification: A Pilot Study                                                      |                             Blood pressure                            |                         CRNN (CNN-LSTM)                        |
| 152 | 2020 |                                                      Photoplethysmography-Based Blood Pressure Estimation Using Deep Learning                                                     |                             Blood pressure                            |                     visibility graph + CNN                     |
| 153 | 2023 |                                   Physical Activity Recognition Based on Deep Learning Using Photoplethysmography and Wearable Inertial Sensors                                   |                       Human activity recognition                      |                            CNN + SE                            |
| 154 | 2022 |                                                 PPG Signal Reconstruction Using Deep Convolutional Generative Adversarial Network                                                 |                           Signal processing                           |                               GAN                              |
| 155 | 2022 |                                          PPG2ABP: Translating Photoplethysmogram (PPG) Signals to Arterial Blood Pressure (ABP) Waveforms                                         |                             Blood pressure                            |                   Unet (1D MultiResUNet)/CNN                   |
| 156 | 2023 | PPG2ECGps: An End-to-End Subject-Specific Deep Neural Network Model for Electrocardiogram Reconstruction from Photoplethysmography Signals without Pulse Arrival Time Adjustments |                           ECG reconstruction                          |                           W Net (CNN)                          |
| 157 | 2018 |                                               PPG-based Heart Rate Estimation with Time-Frequency Spectra: A Deep Learning Approach                                               |                         Cardiovascular system                         |                               CNN                              |
| 158 | 2019 |                                             PPGnet: Deep Network for Device Independent Heart Rate Estimation from Photoplethysmogram                                             |                         Cardiovascular system                         |                         CNN-LSTM(CRNN)                         |
| 159 | 2020 |                                              PP-Net: A Deep Learning Framework for PPG-Based Blood Pressure and Heart Rate Estimation                                             |                  Blood pressure/Cardiovascular system                 |                           LRCN(CRNN)                           |
| 160 | 2023 |                                        Predicting patient decompensation from continuous physiologic monitoring in the emergency department                                       | Blood glucose/Blood pressure/Cardiovascular system/Respiratory system |                         Transformer+ML                         |
| 161 | 2021 |                              Prediction of arterial blood pressure waveforms from photoplethysmogram signals via fully convolutional neural networks                              |                             Blood pressure                            |                            U-Net/CNN                           |
| 162 | 2020 |                                                       Prediction of vascular aging based on smartphone acquired PPG signals                                                       |                         Cardiovascular system                         |                         12-layer ResNet                        |
| 163 | 2020 |                                 Prediction of Ankle Brachial Index with Photoplethysmography Using Convolutional Long Short Term MMental healthry                                 |                         Cardiovascular system                         |                         CNN-LSTM(CRNN)                         |
| 164 | 2021 |                                                    Q-PPG: Energy-Efficient PPG-Based Heart Rate Monitoring on Wearable Devices                                                    |                         Cardiovascular system                         |                               TCN                              |
| 165 | 2023 |                                         Rapid extraction of respiratory waveforms from photoplethysmography: A deep corr-encoder approach                                         |                           Respiratory system                          |                              U-net                             |
| 166 | 2022 |                                  Real-Time Cuffless Continuous Blood Pressure Estimation Using 1D Squeeze U-Net Model: A Progress toward mHealth                                  |                             Blood pressure                            |                      1D Squeeze U-net/CNN                      |
| 167 | 2020 |                                                 Real-Time Cuffless Continuous Blood Pressure Estimation Using Deep Learning Model                                                 |                             Blood pressure                            |                Bi-LSTM with residual connection                |
| 168 | 2022 |                                                      Real-Time PPG-Based HRV Implementation Using Deep Learning and Simulink                                                      |                           Signal processing                           |                              LSTM                              |
| 169 | 2020 |                                                   Reconstructing QRS Complex From PPG by Transformed Attentional Neural Networks                                                  |                           ECG reconstruction                          |                   Transformer/Encoder-Decoder                  |
| 170 | 2018 |                                             Repetitive neural network (RNN) based blood pressure estimation using PPG and ECG signals                                             |                             Blood pressure                            |                             Bi-LSTM                            |
| 171 | 2021 |                                                   Research on Estimation of Blood Glucose Based on PPG and Deep Neural Networks                                                   |                             Blood glucose                             |                               FC                               |
| 172 | 2020 |                                                          Respiratory Rate Estimation using PPG: A Deep Learning Approach                                                          |                           Respiratory system                          |                             ResNet                             |
| 173 | 2019 |                                                RespNet: A deep learning model for extraction of respiration from photoplethysmogram                                               |                           Respiratory system                          |                         Residual U-Net                         |
| 174 | 2021 |                                            RespWatch: Robust Measurement of Respiratory Rate on Smartwatches with Photoplethysmography                                            |                           Respiratory system                          |                          Residual CNN                          |
| 175 | 2022 |                         Res-SE-ConvNet: A Deep Neural Network for Hypoxemia Severity Prediction for Hospital In-patients Using Photoplethysmograph Signal                         |                           Respiratory system                          |                               CNN                              |
| 176 | 2021 |                                      RMSSD Estimation From Photoplethysmography and Accelerometer Signals Using a Deep Convolutional Network                                      |                         Cardiovascular system                         |                               CNN                              |
| 177 | 2021 |                                                            Robust and Energy-efficient PPG-based Heart-Rate Monitoring                                                            |                         Cardiovascular system                         |                               TCN                              |
| 178 | 2020 |                                                    Robust PPG motion artifact detection using a 1-D convolution neural network                                                    |                           Signal processing                           |                             1D-CNN                             |
| 179 | 2022 |                                                       Robust PPG Peak Detection Using Dilated Convolutional Neural Networks                                                       |                           Signal processing                           |                 CNNs with dilated convolutions                 |
| 180 | 2022 |                                            Robust Reconstruction of Electrocardiogram Using Photoplethysmography: A Subject-Based Model                                           |                           ECG reconstruction                          |                     encoder-decoder/BiLSTM                     |
| 181 | 2023 |                                        RRWaveNet: A Compact End-to-End Multi-Scale Residual CNN for Robust PPG Respiratory Rate Estimation                                        |                           Respiratory system                          |                          Residual CNN                          |
| 182 | 2021 |                                       Signal Quality Assessment of PPG Signals using STFT TimeFrequency Spectra and Deep Learning Approaches                                      |                           Signal processing                           |                           STFT + CNN                           |
| 183 | 2022 |                                       SleepPPG-Net: A Deep Learning Algorithm for Robust Sleep Staging From Continuous Photoplethysmography                                       |                              Sleep health                             |                               CNN                              |
| 184 | 2020 |                                   Stochastic Modeling Based Nonlinear Bayesian Filtering for Photoplethysmography Denoising in Wearable Devices                                   |                           Signal processing                           |                               RNN                              |
| 185 | 2020 |                                              Stress Classification Using Photoplethysmogram-Based Spatial and Frequency Domain Images                                             |                             Mental health                             |                               CNN                              |
| 186 | 2022 |                                                        Stress Detection Using PPG Signal and Combined Deep CNN-MLP Network                                                        |                             Mental health                             |                               CNN                              |
| 187 | 2022 |                                               Subject-Based Model for Reconstructing Arterial Blood Pressure from Photoplethysmogram                                              |                             Blood pressure                            |                          W-Net (U-Net)                         |
| 188 | 2023 |                                                            Subject-Independent per Beat PPG to Single-Lead ECG Mapping                                                            |                           ECG reconstruction                          |                   Encoder-Decoder(CNN+BiLSTM)                  |
| 189 | 2021 |                                              The Application of Deep Learning Algorithms for PPG Signal Processing and Classification                                             |                           Signal processing                           |                      Bi-LSTM, CNN, CNN-LSTM                    |
| 190 | 2021 |                                               Transfer learning from ECG to PPG for improved sleep staging from wrist-worn wearables                                              |                              Sleep health                             |                               CNN                              |
| 191 | 2021 |                                        Using CNN and HHT to predict blood pressure level based on photoplethysmography and its derivatives                                        |                             Blood pressure                            |               CNN + Hilbert–Huang Transform (HHT)              |
| 192 | 2020 |                     Wearable monitoring of sleep‑disordered breathing: estimation of the apnea–hypopnea index using wrist‑worn reflective photoplethysmography                    |                              Sleep health                             |                               CNN                              |
| 193 | 2023 |                                        Weighted knowledge distillation of attention-LRCN for recognizing affective states from PPG signals                                        |                             Mental health                             |                        CRNN + attention                        |
